[package]
name = "flux-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[features]
cgo = ["dep:libc"]

[dependencies]
libc = { version = "*", optional = true }
